# Generated by Django 5.0.2 on 2024-03-12 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AuthGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_collation='SQL_Latin1_General_CP1_CI_AS', max_length=150, unique=True)),
            ],
            options={
                'db_table': 'auth_group',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthGroupPermissions',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'auth_group_permissions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthPermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_collation='SQL_Latin1_General_CP1_CI_AS', max_length=255)),
                ('codename', models.CharField(db_collation='SQL_Latin1_General_CP1_CI_AS', max_length=100)),
            ],
            options={
                'db_table': 'auth_permission',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(db_collation='SQL_Latin1_General_CP1_CI_AS', max_length=128)),
                ('last_login', models.DateTimeField()),
                ('is_superuser', models.BooleanField()),
                ('username', models.CharField(db_collation='SQL_Latin1_General_CP1_CI_AS', max_length=150, unique=True)),
                ('first_name', models.CharField(db_collation='SQL_Latin1_General_CP1_CI_AS', max_length=150)),
                ('last_name', models.CharField(db_collation='SQL_Latin1_General_CP1_CI_AS', max_length=150)),
                ('email', models.CharField(db_collation='SQL_Latin1_General_CP1_CI_AS', max_length=254)),
                ('is_staff', models.BooleanField()),
                ('is_active', models.BooleanField()),
                ('date_joined', models.DateTimeField()),
            ],
            options={
                'db_table': 'auth_user',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUserGroups',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'auth_user_groups',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUserUserPermissions',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'auth_user_user_permissions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoAdminLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_time', models.DateTimeField()),
                ('object_id', models.TextField(db_collation='SQL_Latin1_General_CP1_CI_AS')),
                ('object_repr', models.CharField(db_collation='SQL_Latin1_General_CP1_CI_AS', max_length=200)),
                ('action_flag', models.SmallIntegerField()),
                ('change_message', models.TextField(db_collation='SQL_Latin1_General_CP1_CI_AS')),
            ],
            options={
                'db_table': 'django_admin_log',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoContentType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_label', models.CharField(db_collation='SQL_Latin1_General_CP1_CI_AS', max_length=100)),
                ('model', models.CharField(db_collation='SQL_Latin1_General_CP1_CI_AS', max_length=100)),
            ],
            options={
                'db_table': 'django_content_type',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoMigrations',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('app', models.CharField(db_collation='SQL_Latin1_General_CP1_CI_AS', max_length=255)),
                ('name', models.CharField(db_collation='SQL_Latin1_General_CP1_CI_AS', max_length=255)),
                ('applied', models.DateTimeField()),
            ],
            options={
                'db_table': 'django_migrations',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoSession',
            fields=[
                ('session_key', models.CharField(db_collation='SQL_Latin1_General_CP1_CI_AS', max_length=40, primary_key=True, serialize=False)),
                ('session_data', models.TextField(db_collation='SQL_Latin1_General_CP1_CI_AS')),
                ('expire_date', models.DateTimeField()),
            ],
            options={
                'db_table': 'django_session',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Exercise',
            fields=[
                ('exerciseid', models.AutoField(db_column='ExerciseID', primary_key=True, serialize=False)),
                ('exercisename', models.CharField(db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='ExerciseName', max_length=30)),
            ],
            options={
                'db_table': 'Exercise',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Exerciserecord',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('exercise_name', models.CharField(db_collation='SQL_Latin1_General_CP1_CI_AS', max_length=50)),
                ('sets', models.IntegerField()),
                ('reps', models.IntegerField()),
                ('weight', models.FloatField()),
                ('auth_id', models.IntegerField()),
                ('day', models.IntegerField()),
                ('workout_number', models.IntegerField()),
            ],
            options={
                'db_table': 'ExerciseRecord',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Rfauthuser',
            fields=[
                ('id', models.AutoField(db_column='Id', primary_key=True, serialize=False)),
                ('password', models.CharField(db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='Password', max_length=28)),
                ('username', models.CharField(db_collation='SQL_Latin1_General_CP1_CI_AS', max_length=20)),
                ('email_address', models.CharField(db_collation='SQL_Latin1_General_CP1_CI_AS', max_length=255)),
            ],
            options={
                'db_table': 'RFAuthUser',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Workout',
            fields=[
                ('workoutid', models.AutoField(db_column='WorkoutID', primary_key=True, serialize=False)),
                ('workoutday', models.IntegerField(db_column='WorkoutDay')),
            ],
            options={
                'db_table': 'Workout',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Workoutexercise',
            fields=[
                ('workoutexerciseid', models.AutoField(db_column='WorkoutExerciseID', primary_key=True, serialize=False)),
                ('days', models.CharField(db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='Days', max_length=200)),
                ('exercises', models.CharField(db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='Exercises', max_length=200)),
                ('sets', models.CharField(db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='Sets', max_length=200)),
                ('reps', models.CharField(db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='Reps', max_length=200)),
                ('rest', models.CharField(db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='Rest', max_length=200)),
                ('weeks', models.IntegerField(db_column='Weeks')),
                ('authid', models.IntegerField(db_column='AuthID')),
                ('workoutnumber', models.IntegerField(db_column='WorkoutNumber')),
                ('workoutname', models.CharField(db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='WorkoutName', max_length=50)),
            ],
            options={
                'db_table': 'WorkoutExercise',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Workouttemplate',
            fields=[
                ('workouttemplateid', models.AutoField(db_column='WorkoutTemplateID', primary_key=True, serialize=False)),
                ('workoutname', models.CharField(db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='WorkoutName', max_length=200)),
                ('exercises', models.CharField(db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='Exercises', max_length=200)),
                ('sets', models.CharField(db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='Sets', max_length=200)),
                ('reps', models.CharField(db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='Reps', max_length=200)),
                ('rest', models.CharField(db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='Rest', max_length=200)),
                ('days', models.CharField(db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='Days', max_length=200)),
                ('weeks', models.IntegerField(db_column='Weeks')),
            ],
            options={
                'db_table': 'WorkoutTemplate',
                'managed': False,
            },
        ),
    ]
